name: Link Checker

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: actions/cache@v3
        with:
          path:send:cd9b9351fd8ec40c8e82df9803e911c30064c6a07d4e156df2880b2a5290e58c
            ${{ github.workspace }}/**/.cache
          key: |
            ${{ runner.os }}-docusaurus-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-docusaurus-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: cd ./website && yarn

      - name: Run test
        run: cd ./website && yarn full-test
